spring.application.name=architecture

spring.datasource.url=jdbc:postgresql://postgres:5432/architecture
spring.datasource.username=user
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
